Repository boostcampwm-2024/web05-Denamu, pull requests merged in 2024-12, with the labels that each got.

#94 📝 docs: readme 노션 링크 추가
  README.md
  server/src/app.module.ts
Labels: 📝 Docs

#240 🐛 fix: count 정수형으로 변경
  server/src/statistic/dto/platform-response.dto.ts
  server/src/statistic/statistic.service.ts
Labels: 👹 BugFix

#242 ✅ test: 테스트 픽스처 구현
  server/test/feed/fixture/feedFixture.ts
  server/test/fixture/admin.fixture.ts
  server/test/fixture/feed.fixture.ts
  server/test/fixture/rss.fixture.ts
  server/test/fixture/rssAccept.fixture.ts
  server/test/fixture/rssReject.fixture.ts
  server/test/rss/accept.e2e-spec.ts
  server/test/rss/fixture/rssAcceptFixture.ts
  server/test/rss/fixture/rssFixture.ts
  server/test/rss/reject.e2e-spec.ts
  server/test/rss/rss.e2e-spec.ts
  server/test/statistic/platform.e2e-spec.ts
  server/test/statistic/today.e2e-spec.ts
Labels: ✅ Test

#245 ✨ feat: 플로팅 버튼 추가
  client/src/components/chat/ChatButton.tsx
  client/src/components/layout/Header.tsx
  client/src/components/layout/SideButton.tsx
  client/src/components/ui/sidebar.tsx
  server/src/feed/feed.service.ts
Labels: 🔨 Refactor

#254 📝 docs: readme 내용 보완
  README.md
Labels: 📝 Docs

#253 ✨ feat: 차트 컴포넌트 구현, 차트 API연동
  client/package-lock.json
  client/package.json
  client/src/api/services/chart/chart.ts
  client/src/components/chart/BarChartItem.tsx
  client/src/components/chart/Chart.tsx
  client/src/components/chart/ChartSkeleton.tsx
  client/src/components/chart/PieChartItem.tsx
  client/src/components/chat/ChatButton.tsx
  client/src/components/layout/Header.tsx
  client/src/components/layout/SideButton.tsx
  client/src/components/ui/chart.tsx
  client/src/hooks/queries/useChart.ts
  client/src/pages/Home.tsx
  client/src/store/useTapStore.ts
  client/src/types/chart.ts
Labels: ✨ Feature

#263 📝 docs: update README.md
  README.md
Labels: 📝 Docs

#264 ✅ test: 전체 통계 API 테스트 코드 작성
  server/test/statistic/all.e2e-spec.ts
  server/test/statistic/today.e2e-spec.ts
Labels: ✅ Test

#265 ✅ test: 블로그 플랫폼별 통계 API 테스트 코드 작성
  server/test/statistic/platform.e2e-spec.ts
Labels: ✅ Test

#267 ✅ test: RSS 승인/거절 기록 API 테스트 코드 작성
  server/test/rss/history/accept.e2e-spec.ts
  server/test/rss/history/reject.e2e-spec.ts
Labels: ✅ Test

#268 ✅ test: post rss API 테스트 코드 작성
  server/test/rss/dto/rss-register.dto.spec.ts
  server/test/rss/rss.e2e-spec.ts
Labels: ✅ Test

#266 ✅ test: 로그아웃 API 테스트 코드 작성
  server/src/admin/admin.controller.ts
  server/test/admin/logout.e2e-spec.ts
Labels: ✅ Test

#274 🐛 fix: velog rssurl 등록 시 '@'가 없으면 etc로 분류되는 버그 수정
  server/src/rss/rss.service.ts
Labels: 👹 BugFix

#275 📦chore: 프로덕션 서버 위치 변경 및 정적 파일 추가 / 스웨거 endpoint 변경
  .github/workflows/deploy.yml
  server/src/common/swagger/swagger.ts
  static/Denamu_Logo_KOR.png
  static/Denamu_Logo_KOR.webp
  static/github-icon.svg
  static/images.png
  static/medium-icon.svg
  static/tistory-icon.svg
  static/velog-icon.svg
Labels: 🔧 Chore

#228 ✅ test: admin 로그인, admin 회원가입, sessionId 확인 API 테스트 코드 작성
  server/src/admin/admin.api-docs.ts
  server/src/admin/admin.service.ts
  server/test/admin/dto/login-admin.dto.spec.ts
  server/test/admin/dto/register-admin.dto.spec.ts
  server/test/admin/login.e2e-spec.ts
  server/test/admin/register.e2e.spect.ts
  server/test/admin/sessionId.e2e-spec.ts
  server/test/feed/fixture/feedFixture.ts
Labels: ✅ Test, 🧹 Cleanup

#273 ✅ test: SSE 최초 접속 테스트 코드 작성
  server/package-lock.json
  server/package.json
  server/test/feed/trend.e2e-spec.ts
Labels: ✅ Test

#277 ♻️ refactor: swagger 문서, DAO 분리
  server/src/rss/api-docs/acceptRss.api-docs.ts
  server/src/rss/api-docs/createRss.api-docs.ts
  server/src/rss/api-docs/readAcceptHistoryRss.api-docs.ts
  server/src/rss/api-docs/readAllRss.api-docs.ts
  server/src/rss/api-docs/readRejectHistoryRss.api-docs.ts
  server/src/rss/api-docs/rejectRss.api-docs.ts
  server/src/rss/rss.api-docs.ts
  server/src/rss/rss.controller.ts
Labels: 🔨 Refactor

#278 🧼 clean: 네이밍 컨벤션 수정
  server/src/rss/rss.controller.ts
  server/src/rss/rss.service.ts
Labels: 🧹 Cleanup

#282 ✅ test: 최신 피드 업데이트 API 테스트 코드 작성
  server/test/feed/feed.e2e-spec.ts
  server/test/feed/feedId.e2e-spec.ts
  server/test/feed/fixture/feedFixture.ts
  server/test/feed/recent.e2e-spec.ts
Labels: ✅ Test

#279 ♻️ refactor: rss 코드 정리
  rss-notifier/src/common/constant.ts
  rss-notifier/src/common/db-access.ts
  rss-notifier/src/common/logger.ts
  rss-notifier/src/common/types.ts
  rss-notifier/src/main.ts
  rss-notifier/src/rss-notifier.ts
  server/src/rss/rss.service.ts
Labels: 🔨 Refactor

#284 🧼 clean: admin register api의 test 파일명 수정
  server/test/admin/register.e2e-spec.ts
Labels: 🧹 Cleanup

#280 ✨ feat: 채팅 자정 알림 구현
  server/package-lock.json
  server/package.json
  server/src/chat/chat.gateway.ts
Labels: ✨ Feature

#285 ✅ test: search dto 테스트 코드 작성
  server/src/feed/dto/search-feed.dto.ts
  server/test/feed/dto/query-search.dto.spec.ts
Labels: ✅ Test

#281 ✨ feat: PostCard 로드될 때 Skeleton UI 적용
  client/src/components/common/Card/PostCardSkeleton.tsx
  client/src/components/sections/LatestSection.tsx
  client/src/components/sections/TrendingSection.tsx
Labels: ✨ Feature

#276 ✨ feat: 소개 페이지 구현
  client/src/App.tsx
  client/src/components/about/CTASection.tsx
  client/src/components/about/ExtraFeatureSection.tsx
  client/src/components/about/FeatureCard.tsx
  client/src/components/about/FeatureSection.tsx
  client/src/components/about/Footer.tsx
  client/src/components/about/HeroSection.tsx
  client/src/components/about/Section.tsx
  client/src/constants/about.ts
  client/src/constants/footer.ts
  client/src/hooks/common/useInView.ts
  client/src/hooks/common/useScrollProgress.ts
  client/src/pages/AboutService.tsx
  client/src/types/about.ts
  client/src/types/footer.ts
  client/tailwind.config.js
Labels: ✨ Feature

#287 ♻️ refactor: 5주차 피드백 개선
  client/src/components/admin/rss/RssResponseCard.tsx
  client/src/components/chart/PieChartItem.tsx
  client/src/components/chat/Chat.tsx
  client/src/components/chat/ChatItem.tsx
  client/src/components/chat/layout/ChatFooter.tsx
  client/src/components/chat/layout/ChatSection.tsx
  client/src/components/common/Card/PostCardContent.tsx
  client/src/components/search/SearchHigilight.tsx
  client/src/components/search/SearchResults/SearchResultItem.tsx
  client/src/components/search/SearchResults/SearchResultList.tsx
  client/src/components/search/searchPages/SearchPages.tsx
  client/src/hooks/common/useKeyboardShortcut.ts
  client/src/hooks/queries/useChart.ts
  client/src/types/chat.ts
  client/src/types/post.ts
Labels: 🔨 Refactor

#286 🧼 clean: type을 추론할 수 없는 부분 찾아서 타입 명시
  server/src/feed/feed.controller.ts
  server/src/feed/feed.service.ts
Labels: 🧹 Cleanup

#288 🐛 fix: 레디스 저장로직 자정 알림 이벤트에도 추가
  server/src/chat/chat.gateway.ts
Labels: 👹 BugFix, 🧹 Cleanup

#290 ⚡ Performance: 번들 사이즈 줄여 초기 로드 속도 개선하기
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/chart/Chart.tsx
  client/src/components/chart/ChartTab.tsx
  client/src/components/layout/Header.tsx
  client/src/constants/denamuAscii.ts
  client/src/pages/Home.tsx
  client/src/pages/Loading.tsx
  client/vite.config.ts
Labels: ⚡ Performance

#269 ♻️ refactor: admin, statistic 리팩토링
  server/src/admin/admin.controller.ts
  server/src/admin/admin.repository.ts
  server/src/admin/admin.service.ts
  server/src/admin/api-docs/createAdmin.api-docs.ts
  server/src/admin/api-docs/loginAdmin.api-docs.ts
  server/src/admin/api-docs/logoutAdmin.api-docs.ts
  server/src/admin/api-docs/readSessionIdAdmin.api-docs.ts
  server/src/feed/feed.repository.ts
  server/src/statistic/api-docs/readPlatformStatistic.api-docs.ts
  server/src/statistic/api-docs/statistic.api-docs.ts
  server/src/statistic/statistic.controller.ts
  server/src/statistic/statistic.service.ts
  server/test/admin/login.e2e-spec.ts
  server/test/admin/register.e2e-spec.ts
  server/test/admin/sessionId.e2e-spec.ts
Labels: 🔨 Refactor, 🧹 Cleanup

#291 ✅ test: 부하 테스트 작성
  .gitignore
  loadtest/BE_loadtest.json
  loadtest/FE_loadtest.json
  package-lock.json
  package.json
Labels: ✅ Test

#293 ♻️ refactor: 소개 페이지 첫 번째 이미지 서버에서 가져올 수 있도록 변경
  client/src/components/about/HeroSection.tsx
  static/Denamu_Logo_ENG.svg
  static/about-first.png
Labels: 🔨 Refactor

#295 🐛 fix: 블로그 썸네일 상대 경로 문제 해결
  rss-notifier/src/rss-notifier.ts
Labels: 👹 BugFix

#294 📦 chore: Netlify 종속성 제거를 위한 NGINX 설정 변경 및 FE CD 스크립트 작성
  .github/workflows/deploy_client.yml
  .github/workflows/deploy_server.yml
  client/src/api/instance.ts
  client/src/components/about/HeroSection.tsx
  client/src/components/common/Card/PostCardContent.tsx
  client/src/hooks/queries/useTrendingPosts.ts
  client/src/store/useChatStore.ts
  nginx.conf
  server/src/common/email/mail_content.ts
Labels: 🔧 Chore, 🔨 Refactor

#298 ⚡️ perf: 피드 순위 변동이 생길 경우에만 이벤트가 발생하도록 수정
  server/src/feed/feed.service.ts
Labels: ⚡ Performance

#300 📦 chore: Let's Encrypt SSL/TLS 인증서 발급 및 Nginx 설정 추가
  nginx.conf
  server/src/main.ts
Labels: 🔧 Chore

#304 🐛 fix: nginx proxy_read_timeout 1시간으로 설정
  nginx.conf
Labels: 👹 BugFix, 🔧 Chore

#306 ♻️ refactor: RSS 피드 등록 시 플랫폼별 URL 자동 구성 기능 구현
  client/src/components/RssRegistration/FormInput.tsx
  client/src/components/RssRegistration/PlatformSelector.tsx
  client/src/components/RssRegistration/RssRegistrationModal.tsx
  client/src/components/RssRegistration/RssUrlInput.tsx
  client/src/constants/rss.ts
  client/src/hooks/common/useRssRegistrationForm.ts
  client/src/store/.gitkeep
  client/src/store/useRegisterModalStore.ts
Labels: 🔨 Refactor

#303 ⚡️ perf: SEO 메타태그 및 robots.txt 추가
  client/index.html
  client/public/robots.txt
Labels: ⚡ Performance

#311 ⚡️ perf: 피드 삽입 정렬 기능 제거 & 피드 뷰 구현
  .github/workflows/deploy_server.yml
  ecosystem.config.js
  feed-crawler/.gitignore
  feed-crawler/package-lock.json
  feed-crawler/package.json
  feed-crawler/src/common/constant.ts
  feed-crawler/src/common/db-access.ts
  feed-crawler/src/common/logger.ts
  feed-crawler/src/common/types.ts
  feed-crawler/src/feed-crawler.ts
  feed-crawler/src/main.ts
  feed-crawler/tsconfig.json
  server/src/feed/feed.entity.ts
Labels: ⚡ Performance
