Repository boostcampwm-2024/web05-Denamu, pull requests merged in 2024-11, with the labels that each got.

#26 📦 chore: 프론트엔드 개발 환경 세팅
  .gitignore
  .vscode/settings.json
  client/.gitignore
  client/.prettierrc
  client/README.md
  client/eslint.config.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/App.tsx
  client/src/api/queries/.gitkeep
  client/src/assets/.gitkeep
  client/src/components/.gitkeep
  client/src/hooks/.gitkeep
  client/src/index.css
  client/src/main.tsx
  client/src/pages/.gitkeep
  client/src/pages/Home.tsx
  client/src/store/.gitkeep
  client/src/types/.gitkeep
  client/src/utils/.gitkeep
  client/src/vite-env.d.ts
  client/tailwind.config.js
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  server/.gitkeep
Labels: 🔧 Chore

#34 📦 chore: 초기 의존성 설치
  server/.eslintrc.js
  server/.gitignore
  server/.gitkeep
  server/.prettierrc
  server/README.md
  server/nest-cli.json
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/main.ts
  server/test/app.e2e-spec.ts
  server/test/jest-e2e.json
  server/tsconfig.build.json
  server/tsconfig.json
Labels: 🔧 Chore

#36 📦 chore: 커밋린트 설정
  commitlint.config.js
  lefthook.yml
  package-lock.json
  package.json
Labels: 🔧 Chore

#38 📦 chore: 커밋린트 수정
  commitlint.config.js
  lefthook.yml
Labels: 🔧 Chore

#42 📦 chore: CD 파이프라인 작성
  .github/workflows/deploy.yml
  server/ecosystem.config.js
  server/src/app.module.ts
Labels: 🔧 Chore

#43 📦 chore: CD 파이프라인 nvm 환경 변수 명시
  .github/workflows/deploy.yml
  server/package.json
Labels: 👹 BugFix, 🔧 Chore

#39 📦 chore: Nest 환경 로거 등록
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/common/logger/logger.config.ts
  server/src/common/logger/logger.module.ts
Labels: 🔧 Chore

#45 📦 chore: Test 환경 구축 DB Connect
  .github/pull_request_template.md
  .github/workflows/deploy.yml
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/blog/blog.entity.ts
  server/src/common/database/load.config.ts
  server/src/feed/feed.entity.ts
  server/src/login/login.entity.ts
  server/src/rss/rss.entity.ts
Labels: 🔧 Chore, ✅ Test

#46 🐛 fix: CI/CD configs 디렉토리 경로 수정, 피드백 반영
  .github/workflows/deploy.yml
  server/.gitignore
  server/src/configs/.env.db.test
Labels: 👹 BugFix

#47 🐛 fix: CD 스크립트 오탈자 수정
  .github/workflows/deploy.yml
Labels: 👹 BugFix

#48 🐛 fix: 통합, E2E, Unit 테스트 환경 구축
  .github/workflows/deploy.yml
  server/configs/.env.db.test
  server/jest-e2e.json
  server/jest-unit.json
  server/package.json
  server/src/app.module.ts
  server/src/blog/blog.entity.ts
  server/src/common/database/load.config.ts
  server/src/feed/feed.entity.ts
  server/test/app.e2e-spec.ts
  server/test/test.spec.ts
  server/tsconfig.json
Labels: 👹 BugFix, 🔧 Chore, ✅ Test

#51 메인 페이지 (TrandingSection, LatestSeciton) 컴포넌트 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/mockApi.ts
  client/src/components/common/Card/PostCard.tsx
  client/src/components/common/LazyImage.tsx
  client/src/components/common/LoadingIndicator.tsx
  client/src/components/sections/LatestSection.tsx
  client/src/constants/dummyData.ts
  client/src/hooks/useInfiniteScrollQuery.ts
  client/src/lib/utils.ts
  client/src/types/post.ts
  package-lock.json
  package.json
Labels: ✨ Feature

#53 ♻️ refactor: dependencies 제대로 들어가지 않은 부분 수정
  package.json
Labels: 🔨 Refactor, 🚨 P1

#54 ♻️ refactor: 테스트 환경 내부 완전 분리
  server/.gitignore
  server/ecosystem.config.js
  server/package.json
  server/test/jest-e2e.json
  server/test/jest-integration.json
  server/test/jest-unit.json
  server/tsconfig.json
Labels: ✅ Test, 🔨 Refactor

#55 🐛 fix: feed entity viewcount 기본값 설정
  server/src/feed/feed.entity.ts
Labels: 👹 BugFix

#70 ✨ feat: 관리 페이지 UI 구현
  client/.prettierrc
  client/components.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/RssRegistration/FormInput.tsx
  client/src/components/RssRegistration/RssRegistrationModal.tsx
  client/src/components/RssRegistration/RssValidation.ts
  client/src/components/admin/layout/AdminHeader.tsx
  client/src/components/admin/layout/AdminNavigationMenu.tsx
  client/src/components/admin/layout/AdminTabs.tsx
  client/src/components/admin/rss/RejectModal.tsx
  client/src/components/admin/rss/RssRequestCard.tsx
  client/src/components/admin/rss/RssSearchBar.tsx
  client/src/components/common/Card/PostCard.tsx
  client/src/components/layout/Header.tsx
  client/src/components/layout/Layout.tsx
  client/src/components/search/SearchButton.tsx
  client/src/components/sections/MainContent.tsx
  client/src/components/ui/avatar.tsx
  client/src/components/ui/badge.tsx
  client/src/components/ui/button.tsx
  client/src/components/ui/card.tsx
  client/src/components/ui/dialog.tsx
  client/src/components/ui/dropdown-menu.tsx
  client/src/components/ui/input.tsx
  client/src/components/ui/label.tsx
  client/src/components/ui/navigation-menu.tsx
  client/src/components/ui/sheet.tsx
  client/src/components/ui/tabs.tsx
  client/src/components/ui/textarea.tsx
  client/src/components/ui/tooltip.tsx
  client/src/index.css
  client/src/lib/utils.ts
  client/src/pages/Admin.tsx
  client/src/store/useRegisterModalStrore.ts
  client/src/types/post.ts
  client/src/types/rss.ts
  client/tailwind.config.js
  client/tsconfig.app.json
  client/tsconfig.json
Labels: ✨ Feature

#73 🐛 fix: rss-notifier 배포 스크립트 오탈자 및 의존성 추가
  .github/workflows/deploy.yml
  ecosystem.config.js
  rss-notifier/package-lock.json
  rss-notifier/package.json
Labels: 👹 BugFix

#72 📦 chore: redis 환경 구축
  .github/workflows/deploy.yml
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/common/database/load.config.ts
  server/src/redis/redis.module.ts
  server/src/redis/redis.service.ts
Labels: 🔧 Chore, ✅ Test

#74 📦 chore: swagger 환경 구축
  server/src/common/swagger/swagger.ts
  server/src/main.ts
Labels: 🔧 Chore, 📝 Docs

#67 ✨ feat: 검색 컴포넌트 구현
  client/components.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/searchMockApi.ts
  client/src/assets/searchIcon.svg
  client/src/components/layout/Header.tsx
  client/src/components/search/SearchButton.tsx
  client/src/components/search/SearchFilters/FilterButton.tsx
  client/src/components/search/SearchHeader/SearchInput.tsx
  client/src/components/search/SearchModal.tsx
  client/src/components/search/SearchResults/SearchResultItem.tsx
  client/src/components/search/SearchResults/SearchResultList.tsx
  client/src/components/search/searchPages/SearchPages.tsx
  client/src/components/ui/button.tsx
  client/src/components/ui/command.tsx
  client/src/components/ui/dialog.tsx
  client/src/components/ui/pagination.tsx
  client/src/constants/dummySearchData.ts
  client/src/hooks/useKeyboardShortcut.ts
  client/src/hooks/useSearch.ts
  client/src/lib/utils.ts
  client/src/store/useSearchStore.ts
  client/src/types/search.ts
  client/src/utils/pagination.ts
Labels: ✨ Feature

#77 🐛 fix: Header컴포넌트 반응형 Sidebar 에러 수정
  client/src/components/RssRegistration/RssRegistrationModal.tsx
  client/src/components/layout/Header.tsx
  client/src/components/layout/Sidebar.tsx
Labels: 👹 BugFix

#76 ✨ feat: ApiResponse dto 및 전역 예외 필터 작성
  server/src/common/filters/global-exceptions.filter.ts
  server/src/common/response/common.response.ts
  server/src/main.ts
Labels: ✨ Feature

#79 🐛 fix: Header컴포넌트 중복 import 제거
  client/src/components/layout/Header.tsx
Labels: 👹 BugFix

#84 📦 chore: commitizen clean 태그 추가
  .cz-config.js
  commitlint.config.js
Labels: 🔧 Chore

#85 💄 style: eslint eof 오토 설정 추가
  server/.eslintrc.js
Labels: 🔧 Chore

#80 ✨ feat: RSS 전체 조회 API 구현
  server/src/rss/dto/rss-register.dto.ts
  server/src/rss/rss.api-docs.ts
  server/src/rss/rss.controller.ts
  server/src/rss/rss.service.ts
Labels: ✨ Feature

#89 ✨ feat: CORS 허용 설정
  server/package.json
  server/src/main.ts
Labels: 🔧 Chore

#81 ✨ feat: 관리자 로그인 API 구현
  server/package-lock.json
  server/package.json
  server/src/account/account.api-docs.ts
  server/src/account/account.controller.ts
  server/src/account/account.module.ts
  server/src/account/account.service.ts
  server/src/account/dto/login-admin.dto.ts
  server/src/common/cookie/cookie.config.ts
  server/src/main.ts
  server/src/redis/redis.module.ts
Labels: ✨ Feature

#90 ✨ feat: 메인 화면 게시글 목록 조회 API 구현
  server/src/account/account.controller.ts
  server/src/account/account.service.ts
  server/src/account/dto/login-admin.dto.ts
  server/src/app.module.ts
  server/src/feed/dto/query-feed.dto.ts
  server/src/feed/feed.api-docs.ts
  server/src/feed/feed.controller.ts
  server/src/feed/feed.module.ts
  server/src/feed/feed.repository.ts
  server/src/feed/feed.service.ts
Labels: ✨ Feature

#92 ✨ feat: 관리자 로그인 페이지 구현
  client/src/components/RssRegistration/FormInput.tsx
  client/src/components/admin/layout/AdminHeader.tsx
  client/src/components/admin/login/AdminLoginModal.tsx
  client/src/components/layout/Header.tsx
  client/src/components/layout/Sidebar.tsx
  client/src/pages/Admin.tsx
Labels: ✨ Feature

#98 🐛 fix: RSS 등록 API 명세 변경에 따른 수정
  server/src/rss/dto/rss-register.dto.ts
  server/src/rss/rss.entity.ts
  server/src/rss/rss.repository.ts
  server/src/rss/rss.service.ts
Labels: 👹 BugFix

#100 🐛 fix: production-port 변경
  .github/workflows/deploy.yml
Labels: 👹 BugFix

#101 ✅ test: RSS 신청 테스트 코드 rssURL -> rssUrl 변경
  server/test/rss/rss.e2e-spec.ts
Labels: 👹 BugFix, ✅ Test

#87 ✨ feat: RSS 승인 및 거절 API 구현
  server/src/blog/blog.entity.ts
  server/src/rss/rss.api-docs.ts
  server/src/rss/rss.controller.ts
  server/src/rss/rss.entity.ts
  server/src/rss/rss.service.ts
Labels: ✨ Feature

#102 🐛 Winston 로깅 안 되는 버그 수정, 자동 로깅, Exception Filter 분리
  server/src/account/account.api-docs.ts
  server/src/account/account.controller.ts
  server/src/account/account.module.ts
  server/src/account/account.service.ts
  server/src/app.module.ts
  server/src/blog/blog.entity.ts
  server/src/common/filters/global-exceptions.filter.ts
  server/src/common/filters/http-exception.filter.ts
  server/src/common/filters/internal-exceptions.filter.ts
  server/src/common/logger/logger.config.ts
  server/src/common/logger/logger.interceptor.ts
  server/src/common/logger/logger.module.ts
  server/src/common/logger/logger.service.ts
  server/src/common/redis/redis.module.ts
  server/src/common/redis/redis.service.ts
  server/src/feed/feed.controller.ts
  server/src/feed/feed.module.ts
  server/src/main.ts
  server/src/rss/rss.controller.ts
  server/test/rss/rss.e2e-spec.ts
Labels: ✨ Feature, 👹 BugFix, ✅ Test, 🔨 Refactor, 🧹 cleanup

#105 🐛 fix: limit이 string으로 연산되는 버그 수정
  server/src/feed/feed.controller.ts
Labels: 👹 BugFix

#108 ✨ feat: RSS등록 API 연동
  client/.gitignore
  client/src/api/instance.ts
  client/src/api/queries/rssApi.ts
  client/src/components/RssRegistration/RssRegistrationModal.tsx
  client/src/components/RssRegistration/RssValidation.ts
  client/src/hooks/useRegisterRss.ts
  client/src/types/rss.ts
Labels: ✨ Feature

#112 ♻️ refactor: 무한 스크롤 페이지네이션 API 명세와 맞추기
  client/src/api/instance.ts
  client/src/api/mocks/data/posts.ts
  client/src/api/mocks/handlers/posts.ts
  client/src/api/posts.ts
  client/src/components/sections/LatestSection.tsx
  client/src/constants/dummyData.ts
  client/src/hooks/useInfiniteScrollQuery.ts
  client/src/main.tsx
  client/src/types/post.ts
Labels: 🔨 Refactor

#118 🐛 fix: 새롭게 등록된 도메인 cors 설정 추가
  server/src/main.ts
Labels: 👹 BugFix, 🔧 Chore

#117 ✨ feat: 트랜드 게시글 4개 추출 API 구현
  server/src/common/filters/http-exception.filter.ts
  server/src/feed/feed.api-docs.ts
  server/src/feed/feed.controller.ts
  server/src/feed/feed.entity.ts
  server/src/feed/feed.repository.ts
  server/src/feed/feed.service.ts
  server/test/feed/trend.e2e-spec.ts
Labels: ✨ Feature, ✅ Test

#126 🐛 fix: cloudflare IP만 뜨던 문제 수정, 실제 클라이언트 IP 로깅
  server/src/common/logger/logger.interceptor.ts
Labels: 👹 BugFix

#114 ✨ feat: RSS 등록 승인 혹은 거부 시 신청자 메일로 알림 전송
  .github/workflows/deploy.yml
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/common/email/email.module.ts
  server/src/common/email/email.service.ts
  server/src/rss/rss.service.ts
Labels: ✨ Feature

#128 🐛 fix: 테스트 환경 주소 로깅 에러사항 처리
  server/src/common/logger/logger.interceptor.ts
Labels: 👹 BugFix, ✅ Test

#129 🐛 fix: PostCard에 thumbnail과 클릭 시 해당 글로 들어갈 수 있도록 변경
  client/src/api/mocks/data/posts.ts
  client/src/components/common/Card/PostCard.tsx
  client/src/constants/dummyData.ts
  client/src/types/post.ts
Labels: 👹 BugFix

#116 🐛 fix: feed 관련 버그 수정, 쿠키 sameSite 옵션 수정
  server/src/common/cookie/cookie.config.ts
  server/src/feed/dto/feed-response.dto.ts
  server/src/feed/feed.api-docs.ts
  server/src/feed/feed.repository.ts
  server/src/feed/feed.service.ts
  server/src/rss/rss.service.ts
Labels: 👹 BugFix

#125 ✨ feat: 트랜드 스케쥴러, SSE 구현
  server/package-lock.json
  server/package.json
  server/src/feed/feed.api-docs.ts
  server/src/feed/feed.controller.ts
  server/src/feed/feed.module.ts
  server/src/feed/feed.service.ts
  server/test/feed/trend.e2e-spec.ts
Labels: ✨ Feature

#137 🧼 clean: trendData -\> data API 명세에 맞춰서 작성
  server/src/feed/feed.controller.ts
Labels: 👹 BugFix

#143 ⚡️ perf: rss 등록 정보 조회 비동기 처리
  server/src/rss/rss.service.ts
Labels: ⚡ Performance

#135 ✨ feat: 관리자 페이지 로그인, rss승인 거부
  client/src/api/instance.ts
  client/src/api/queries/admin/auth.ts
  client/src/api/queries/admin/rss.ts
  client/src/components/RssRegistration/FormInput.tsx
  client/src/components/admin/layout/AdminTabs.tsx
  client/src/components/admin/login/AdminLoginModal.tsx
  client/src/components/admin/rss/RejectModal.tsx
  client/src/components/admin/rss/RssRequestCard.tsx
  client/src/hooks/useAdminAuth.ts
  client/src/hooks/useFetchRss.ts
  client/src/hooks/useRssActions.ts
  client/src/pages/Admin.tsx
  client/src/store/useAuthStore.ts
  client/src/types/auth.ts
  client/src/types/rss.ts
Labels: ✨ Feature

#142 ✨ feat: 검색api연동, 검색어 하이라이팅
  client/src/api/queries/search.ts
  client/src/api/searchMockApi.ts
  client/src/components/layout/Header.tsx
  client/src/components/search/SearchFilters/FilterButton.tsx
  client/src/components/search/SearchHigilight.tsx
  client/src/components/search/SearchModal.tsx
  client/src/components/search/SearchResults/SearchResultItem.tsx
  client/src/components/search/SearchResults/SearchResultList.tsx
  client/src/hooks/useKeyboardShortcut.ts
  client/src/hooks/useSearch.ts
  client/src/store/useSearchStore.ts
  client/src/types/search.ts
  client/src/utils/debounce.ts
Labels: ✨ Feature

#144 ✨ feat: 트렌딩 포스트 실시간 조회 API 연동
  client/src/api/posts.ts
  client/src/api/queries/.gitkeep
  client/src/api/queries/posts.ts
  client/src/components/sections/LatestSection.tsx
  client/src/components/sections/TrendingSection.tsx
  client/src/hooks/useTrendingPosts.ts
  client/src/types/post.ts
Labels: ✨ Feature

#148 ✨ feat: 채팅 웹소켓 서버 구현
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/chat/chat.gateway.ts
  server/src/chat/chat.module.ts
  server/src/feed/dto/feed-response.dto.ts
  server/src/main.ts
Labels: ✨ Feature

#151 ♻️ refactor: favicon, title 태그 변경, 폰트 pretendard 적용
  client/index.html
  client/src/assets/logo-denamu-main.svg
  client/src/assets/logo-denamu-title.svg
  client/src/index.css
Labels: 🔨 Refactor

#157 🐛 fix: PM2 프로세스 수 조정, chat history 역순
  ecosystem.config.js
  server/src/chat/chat.gateway.ts
Labels: 👹 BugFix

#155 ✨ feat: 검색 결과 relevance 기반 정렬 구현
  server/src/feed/feed.service.ts
Labels: ✨ Feature, ⚡ Performance

#156 🐛 fix: RSS 관리 파이프라인 개선 및 버그 수정
  rss-notifier/package-lock.json
  rss-notifier/package.json
  rss-notifier/src/db-access.ts
  rss-notifier/src/rss-notifier.ts
Labels: 👹 BugFix, 🔨 Refactor

#153 ✨ feat: 조회수 업데이트 API 연동
  client/src/api/services/admin/auth.ts
  client/src/api/services/admin/rss.ts
  client/src/api/services/posts.ts
  client/src/api/services/rss.ts
  client/src/api/services/search.ts
  client/src/api/services/view.ts
  client/src/components/RssRegistration/RssRegistrationModal.tsx
  client/src/components/admin/layout/AdminTabs.tsx
  client/src/components/admin/login/AdminLoginModal.tsx
  client/src/components/common/Card/PostCard.tsx
  client/src/components/common/Card/PostCardContent.tsx
  client/src/components/common/Card/PostCardImage.tsx
  client/src/components/layout/Header.tsx
  client/src/components/search/SearchResults/SearchResultList.tsx
  client/src/components/sections/LatestSection.tsx
  client/src/components/sections/TrendingSection.tsx
  client/src/hooks/common/useKeyboardShortcut.ts
  client/src/hooks/common/usePostCardActions.ts
  client/src/hooks/queries/useAdminAuth.ts
  client/src/hooks/queries/useFetchRss.ts
  client/src/hooks/queries/useInfiniteScrollQuery.ts
  client/src/hooks/queries/usePostViewIncrement.ts
  client/src/hooks/queries/useRegisterRss.ts
  client/src/hooks/queries/useRssActions.ts
  client/src/hooks/queries/useSearch.ts
  client/src/hooks/queries/useTrendingPosts.ts
  client/src/hooks/usePosts.ts
  client/src/utils/pipe.ts
Labels: ✨ Feature

#160 🐛 fix: dto 블로그이름 수정
  server/src/feed/dto/feed-response.dto.ts
Labels: 👹 BugFix

#167 ♻️ refactor: 조회수 증가 API의 메서드를 Post 방식으로 변경
  server/src/feed/feed.controller.ts
Labels: 🔨 Refactor

#184 ♻️ refactor: 메인 페이지 로고 사이즈 변경
  client/src/components/layout/Header.tsx
Labels: 🔨 Refactor

#185 ♻️ refactor: 순위 변경 시 나타나는 파란색 border 삭제 및 usePositionTracking 분리
  client/src/components/sections/AnimatedPostGrid.tsx
  client/src/hooks/common/usePositionTracking.ts
Labels: 🔨 Refactor

#191 ♻️ refactor: 카드 크기 일관성을 위한 Ellipsis 처리 및 고정 높이 설정
  client/src/components/common/Card/PostCard.tsx
  client/src/components/common/Card/PostCardContent.tsx
  client/src/components/common/Card/PostCardImage.tsx
Labels: 🔨 Refactor

#190 🐛 fix: 어드민 계정 생성 시 기존 어드민 계정 로그인 시에만 생성할 수 있도록 가드 적용
  server/src/admin/admin.api-docs.ts
  server/src/admin/admin.controller.ts
  server/src/common/guard/auth.guard.ts
Labels: 👹 BugFix

#192 ♻️ refactor: trend Interval 수정, GET /api/trend Deprecated
  server/src/feed/feed.api-docs.ts
  server/src/feed/feed.controller.ts
  server/src/feed/feed.service.ts
  server/test/feed/trend.e2e-spec.ts
Labels: ✅ Test, 🔨 Refactor

#194 ♻️ refactor: 트렌딩 포스트 점선을 그림자로 변경, 최신 포스트 점선 제거
  client/src/components/sections/LatestSection.tsx
  client/src/components/sections/TrendingSection.tsx
Labels: 🔨 Refactor

#193 ✨ feat: 어드민 페이지 출력 시 세션 아이디를 검증하기 위한 API 추가
  server/src/admin/admin.api-docs.ts
  server/src/admin/admin.controller.ts
Labels: ✨ Feature

#168 ✨ feat: 미구현 기능에 대한 토스트 알림 시스템 구축
  client/package-lock.json
  client/package.json
  client/src/components/layout/Header.tsx
  client/src/components/layout/Layout.tsx
  client/src/components/ui/toast.tsx
  client/src/components/ui/toaster.tsx
  client/src/constants/messages.ts
  client/src/hooks/common/useCustomToast.ts
Labels: ✨ Feature

#197 ♻️ refactor: 메인 페이지 Header 버튼 primary로 변경
  client/src/components/RssRegistration/FormInput.tsx
  client/src/components/RssRegistration/RssRegistrationModal.tsx
  client/src/components/chat/ChatButton.tsx
  client/src/components/chat/layout/ChatFooter.tsx
  client/src/components/chat/layout/ChatHeader.tsx
  client/src/components/layout/Header.tsx
  client/src/components/search/SearchButton.tsx
  client/src/components/sections/TrendingSection.tsx
  client/src/index.css
Labels: 🔨 Refactor

#186 ✨ feat: rss 등록 기록 조회 API 및 트랜잭션 적용
  ecosystem.config.js
  rss-notifier/src/db-access.ts
  rss-notifier/src/rss-notifier.ts
  rss-notifier/src/types.ts
  server/src/blog/blog.entity.ts
  server/src/blog/blog.repository.ts
  server/src/feed/feed.entity.ts
  server/src/feed/feed.service.ts
  server/src/rss/dto/rss-reject.dto.ts
  server/src/rss/rss.api-docs.ts
  server/src/rss/rss.controller.ts
  server/src/rss/rss.entity.ts
  server/src/rss/rss.module.ts
  server/src/rss/rss.repository.ts
  server/src/rss/rss.service.ts
  server/test/rss/rss.e2e-spec.ts
Labels: ✨ Feature

#187 ✨ feat: rss 등록 거절 시 메일에 거절 사유 포함
  server/src/common/email/email.service.ts
  server/src/common/email/mail_content.ts
  server/src/rss/rss.service.ts
Labels: ✨ Feature

#207 📦 chore: 도메인 이전에 따른 경로 변수 변경
  client/src/api/instance.ts
  client/src/hooks/queries/useTrendingPosts.ts
  client/src/store/useChatStore.ts
  server/src/main.ts
Labels: 🔧 Chore

#200 ✨ feat: rss-notifier html element 처리 추가 및 채팅 메시지 escape 제거
  rss-notifier/src/rss-notifier.ts
  server/package-lock.json
  server/package.json
  server/src/chat/chat.gateway.ts
Labels: ✨ Feature, 🔧 Chore

#196 ♻️ refactor: 채팅 컴포넌트 Sidebar로 변경
  client/package-lock.json
  client/package.json
  client/src/components/chat/Chat.tsx
  client/src/components/chat/ChatButton.tsx
  client/src/components/chat/layout/ChatFooter.tsx
  client/src/components/chat/layout/ChatHeader.tsx
  client/src/components/chat/layout/ChatSection.tsx
  client/src/components/chat/layout/ChatSkeleton.tsx
  client/src/components/layout/Header.tsx
  client/src/components/ui/navigation-menu.tsx
  client/src/components/ui/sidebar.tsx
  client/src/components/ui/skeleton.tsx
  client/src/index.css
  client/tailwind.config.js
Labels: 🔨 Refactor

#198 ⚡️ perf: 서버 안정성 향상을 위한 채팅 서버 최대 사용자 제한 추가
  server/src/chat/chat.gateway.ts
Labels: ⚡ Performance

#215 📝 docs: swagger 데코레이터 코드 일관성 개선
  server/src/admin/admin.api-docs.ts
  server/src/feed/feed.api-docs.ts
  server/src/rss/rss.api-docs.ts
Labels: 📝 Docs, 🧹 Cleanup

#214 ✨ feat: 금일 게시글 조회수 통계 API 구현
  server/src/app.module.ts
  server/src/statistic/dto/statistic-query.dto.ts
  server/src/statistic/statistic.api-docs.ts
  server/src/statistic/statistic.controller.ts
  server/src/statistic/statistic.module.ts
  server/src/statistic/statistic.service.ts
  server/test/jest-e2e.json
  server/test/jest-integration.json
  server/test/jest.setup.ts
  server/test/rss/rss.e2e-spec.ts
  server/test/statistic/today.e2e-spec.ts
Labels: ✨ Feature, ✅ Test

#208 ✨ feat: rSS 등록 승인 시 RSS URL을 분석하여 블로그 플랫폼을 등록하는 로직 추가
  server/src/feed/dto/feed-response.dto.ts
  server/src/feed/feed.api-docs.ts
  server/src/feed/feed.service.ts
  server/src/rss/rss.entity.ts
  server/src/rss/rss.service.ts
Labels: ✨ Feature

#218 ♻️ refactor: 헤더 검색 버튼 스타일 수정, 채팅 버튼 스타일 수정
  client/src/components/chat/Chat.tsx
  client/src/components/layout/Header.tsx
  client/src/components/search/SearchButton.tsx
  client/src/components/search/SearchResults/SearchResultList.tsx
  client/src/components/ui/sidebar.tsx
Labels: 🔨 Refactor

#223 🐛 fix: 쿠키 Redis String Key 일 경우 Login 보안 버그 수정
  server/src/admin/admin.controller.ts
  server/src/admin/admin.service.ts
  server/src/common/guard/auth.guard.ts
  server/test/statistic/today.e2e-spec.ts
Labels: 👹 BugFix

#221 ✨ feat: rSS 등록 모달 도움말 추가
  client/package-lock.json
  client/package.json
  client/src/components/RssRegistration/RssRegistrationModal.tsx
  client/src/components/ui/accordion.tsx
  client/tailwind.config.js
Labels: ✨ Feature

#226 ✨ feat: logout API 구현
  server/src/admin/admin.api-docs.ts
  server/src/admin/admin.controller.ts
  server/src/admin/admin.service.ts
Labels: ✨ Feature

#229 ✨ feat: 로그아웃 기능 추가
  client/package-lock.json
  client/package.json
  client/src/api/services/admin/auth.ts
  client/src/assets/lottie/login.json
  client/src/assets/lottie/login.tsx
  client/src/components/admin/layout/AdminHeader.tsx
  client/src/pages/Admin.tsx
Labels: ✨ Feature

#233 🐛 fix: 의존성 핫픽스
  client/package-lock.json
Labels: 👹 BugFix

#235 📝 docs: history API description, blogPlatform 추가
  server/src/rss/rss.api-docs.ts
Labels: 📝 Docs

#232 🐛 fix: gmail 에서 로고 안 뜨는 문제 해결
  server/src/common/email/mail_content.ts
Labels: 👹 BugFix

#234 ♻️ refactor: 채팅창 500명 제한
  client/src/components/RssRegistration/RssRegistrationModal.tsx
  client/src/components/chat/Chat.tsx
  client/src/components/chat/ChatButton.tsx
  client/src/components/chat/layout/ChatHeader.tsx
  client/src/components/chat/layout/ChatSection.tsx
  client/src/components/search/SearchButton.tsx
Labels: 🔨 Refactor

#237 🐛 fix: 헤더 버튼 zindex 수정
  client/src/components/layout/Header.tsx
Labels: 👹 BugFix

#238 💄 style: 채팅 footer 스타일 수정
  client/src/components/chat/layout/ChatFooter.tsx
Labels: 🔨 Refactor

#224 ✅ test: Rss 전체 조회, 승인, 거절 및 검색 API 테스트 코드 작성
  server/src/admin/admin.module.ts
  server/src/feed/feed.module.ts
  server/src/rss/dto/rss-management.dto.ts
  server/src/rss/dto/rss-register.dto.ts
  server/src/rss/dto/rss-reject.dto.ts
  server/src/rss/rss.controller.ts
  server/src/rss/rss.module.ts
  server/src/rss/rss.service.ts
  server/test/feed/fixture/feedFixture.ts
  server/test/jest.setup.ts
  server/test/rss/accept.e2e-spec.ts
  server/test/rss/dto/rss-management.dto.spec.ts
  server/test/rss/fixture/rssAcceptFixture.ts
  server/test/rss/fixture/rssFixture.ts
  server/test/rss/reject.e2e-spec.ts
  server/test/rss/rss.e2e-spec.ts
  server/test/statistic/all.e2e-spec.ts
  server/test/statistic/today.e2e-spec.ts
Labels: ✅ Test

#225 ✨ feat: 블로그 플랫폼별 통계 API 구현
  server/package.json
  server/src/admin/admin.service.ts
  server/src/rss/rss.repository.ts
  server/src/statistic/statistic.api-docs.ts
  server/src/statistic/statistic.controller.ts
  server/src/statistic/statistic.module.ts
  server/src/statistic/statistic.service.ts
  server/test/statistic/all.e2e-spec.ts
  server/test/statistic/platform.e2e-spec.ts
  server/test/statistic/today.e2e-spec.ts
Labels: ✨ Feature

#216 ✨ feat: 최신 게시글 실시간 업데이트 API 구현
  .github/workflows/deploy.yml
  rss-notifier/package-lock.json
  rss-notifier/package.json
  rss-notifier/src/db-access.ts
  rss-notifier/src/rss-notifier.ts
  server/src/common/redis/redis.constant.ts
  server/src/feed/feed.api-docs.ts
  server/src/feed/feed.controller.ts
  server/src/feed/feed.service.ts
Labels: ✨ Feature
