Repository boostcampwm-2024/web05-Denamu, pull requests merged in 2025-08, with the labels that each got.

#438 ♻️ refactor: rss 파싱 로직 개선 (새로운 형식 지원)
  feed-crawler/src/common/parser/base-feed-parser.ts
  feed-crawler/src/common/parser/feed-parser-manager.ts
  feed-crawler/src/common/parser/formats/atom10-parser.ts
  feed-crawler/src/common/parser/formats/rss20-parser.ts
  feed-crawler/src/common/parser/utils/parser-util.ts
  feed-crawler/src/container.ts
  feed-crawler/src/feed-crawler.ts
  feed-crawler/src/main.ts
  feed-crawler/src/types/dependency-symbols.ts
  feed-crawler/test/e2e/claude-ai.e2e-spec.ts
  feed-crawler/test/e2e/feed-crawling.e2e-spec.ts
  feed-crawler/test/setup/testContext.setup.ts
  feed-crawler/test/unit/parser.spec.ts
Labels: 🔨 Refactor

#446 🐛 fix: 컨테이너 재생성 실패문제 해결
  .github/workflows/deploy_feed-crawler.yml
  .github/workflows/deploy_server.yml
Labels: 👹 BugFix

#449 📝 docs: 파일 업로드 API Swagger 작성
  server/src/app.module.ts
  server/src/common/swagger/swagger.ts
  server/src/file/api-docs/deleteFile.api-docs.ts
  server/src/file/api-docs/uploadProfileFile.api-docs.ts
  server/src/file/controller/file.controller.ts
  server/src/file/dto/createFile.dto.ts
  server/src/file/service/file.service.ts
Labels: 📝 Docs

#448 ✨ feat: Feed 조회 시 댓글 수 데이터 제공
  server/src/comment/service/comment.service.ts
  server/src/common/database/migration/1754027996037-AlterFeedCommentCountColumn.ts
  server/src/feed/api-docs/readFeedDetail.api-docs.ts
  server/src/feed/api-docs/readFeedPagination.api-docs.ts
  server/src/feed/api-docs/readRecentFeedList.api-docs.ts
  server/src/feed/api-docs/readTrendFeedList.api-docs.ts
  server/src/feed/api-docs/searchFeedList.api-docs.ts
  server/src/feed/dto/response/feed-detail.dto.ts
  server/src/feed/dto/response/feed-pagination.dto.ts
  server/src/feed/dto/response/recent.dto.ts
  server/src/feed/dto/response/search-feed.dto.ts
  server/src/feed/entity/feed.entity.ts
  server/test/fixture/feed.fixture.ts
Labels: ✨ Feature
