Repository boostcampwm-2024/web05-Denamu, pull requests merged in 2025-01, with the labels that each got.

#312 🐛 fix: Nginx Forwarded-IP 전달 설정 및 채팅 날짜 알림 로직 수정
  nginx.conf
  server/src/chat/chat.gateway.ts
  server/src/common/logger/logger.interceptor.ts
  server/src/feed/feed.service.ts
Labels: 👹 BugFix, 🔧 Chore

#314 ♻️ refactor: 트렌드 데이터 뷰를 통해 검색하도록 변경
  feed-crawler/src/common/constant.ts
  feed-crawler/src/common/db-access.ts
  feed-crawler/src/common/mysql-access.ts
  feed-crawler/src/common/redis-access.ts
  feed-crawler/src/common/types.ts
  feed-crawler/src/feed-crawler.ts
  feed-crawler/src/main.ts
  feed-crawler/src/repository/feed.repository.ts
  feed-crawler/src/repository/rss.repository.ts
  server/src/common/redis/redis.constant.ts
  server/src/feed/api-docs/readFeedPagination.api-docs.ts
  server/src/feed/api-docs/readRecentFeedList.api-docs.ts
  server/src/feed/dto/feed-response.dto.ts
  server/src/feed/feed.controller.ts
  server/src/feed/feed.entity.ts
  server/src/feed/feed.module.ts
  server/src/feed/feed.repository.ts
  server/src/feed/feed.service.ts
  server/test/feed/recent.e2e-spec.ts
Labels: ✨ Feature, ✅ Test, 🔨 Refactor

#316 🐛 fix: import 및 경로 오탈자 수정
  feed-crawler/src/main.ts
  feed-crawler/src/repository/feed.repository.ts
  feed-crawler/src/repository/rss.repository.ts
Labels: 👹 BugFix

#317 🐛 fix: 채팅 자정 Cron 동작을 위한 ScheduleModule 임포트
  server/src/chat/chat.gateway.ts
  server/src/chat/chat.module.ts
Labels: 👹 BugFix

#319 ✨ feat: RSS 승인 시, 피드 가져오는 기능 구현
  feed-crawler/package-lock.json
  feed-crawler/package.json
  feed-crawler/src/feed-crawler.ts
  feed-crawler/src/main.ts
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/feed/feed.repository.ts
  server/src/rss/feed-crawler.service.ts
  server/src/rss/rss-parser.service.ts
  server/src/rss/rss.module.ts
  server/src/rss/rss.service.ts
  server/test/rss/accept.e2e-spec.ts
Labels: ✨ Feature
