Repository boostcampwm-2024/web05-Denamu, pull requests merged in 2025-03, with the labels that each got.

#322 ✨ feat: User, Activity 엔티티 및 기본 레포지토리 작성
  server/src/activity/entity/activity.entity.ts
  server/src/activity/module/activity.module.ts
  server/src/activity/repository/activity.repository.ts
  server/src/app.module.ts
  server/src/user/entity/user.entity.ts
  server/src/user/module/user.module.ts
  server/src/user/repository/user.repository.ts
Labels: ✨ Feature

#334 🐛 fix: docker compose 운영 인프라 include 오류
  .github/workflows/deploy_server.yml
  docker-compose/docker-compose.prod.yml
  feed-crawler/docker/Dockerfile.dev
  feed-crawler/docker/Dockerfile.local
Labels: 👹 BugFix

#339 📦 chore: 간편하게 Docker-Compose 실행하기
  package.json
Labels: 🔧 Chore

#340 📦 chore: cI/CD Ubuntu 환경변수 추가
  .github/workflows/deploy_feed-crawler.yml
  .github/workflows/deploy_server.yml
Labels: 🔧 Chore

#324 ✨ feat: 첫 방문 사용자 about페이지로 리다이렉트
  client/src/App.tsx
  client/src/components/sections/MainContent.tsx
  client/src/store/useVisitStore.ts
Labels: ✨ Feature

#353 📦 chore: vite 개발용 포트 cors 허용
  server/src/main.ts
Labels: 🔧 Chore

#343 ✨ feat: 사용자 회원가입 API 구현
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/common/email/email.service.ts
  server/src/common/email/mail_content.ts
  server/src/user/controller/user.controller.ts
  server/src/user/dto/request/signup.dto.ts
  server/src/user/entity/user.entity.ts
  server/src/user/module/user.module.ts
  server/src/user/service/user.service.ts
  server/src/user/user.constants.ts
Labels: ✨ Feature

#355 ✨ feat: 로그인 API 구현
  .github/workflows/deploy_server.yml
  server/env/.env.local
  server/package-lock.json
  server/package.json
  server/src/common/logger/logger.interceptor.ts
  server/src/user/controller/user.controller.ts
  server/src/user/dto/request/login.dto.ts
  server/src/user/entity/user.entity.ts
  server/src/user/module/user.module.ts
  server/src/user/service/user.service.ts
Labels: ✨ Feature

#357 ✨ feat: 비밀번호 암호화 로직 추가
  server/src/user/service/user.service.ts
Labels: ✨ Feature

#360 ✅ test: 회원가입 관련 테스트 코드 작성
  server/src/user/api-docs/check-email-duplication.api-docs.ts
  server/src/user/api-docs/registerUser.api-docs.ts
  server/src/user/controller/user.controller.ts
  server/src/user/dto/request/check-email-duplication.dto.ts
  server/src/user/dto/request/register.dto.ts
  server/src/user/service/user.service.ts
  server/test/fixture/user.fixture.ts
  server/test/user/dto/certficiate.dto.spec.ts
  server/test/user/dto/check-email-duplication.dto.spec.ts
  server/test/user/dto/register.dto.spec.ts
  server/test/user/e2e/certificate.e2e-spec.ts
  server/test/user/e2e/emailCheck.e2e-spec.ts
  server/test/user/e2e/register.e2e-spec.ts
Labels: 👹 BugFix, ✅ Test

#359 🐛 fix: 채팅/트렌딩 포스트 없을 시 대체UI렌더링
  client/src/assets/empty-panda.svg
  client/src/components/chat/layout/ChatSection.tsx
  client/src/components/common/EmptyPost.tsx
  client/src/components/sections/AnimatedPostGrid.tsx
  client/src/components/sections/TrendingSection.tsx
  client/src/store/useChatStore.ts
Labels: 👹 BugFix

#358 ✨ feat: 플랫폼별 URL 자동 구성 UX 개선
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/components/RssRegistration/PlatformBadge.tsx
  client/src/components/RssRegistration/PlatformSelector.tsx
  client/src/components/RssRegistration/RssRegistrationModal.tsx
  client/src/components/RssRegistration/RssValidation.ts
  client/src/components/ui/popover.tsx
  client/src/components/ui/select.tsx
  client/src/hooks/common/useRssRegistrationForm.ts
  client/src/types/rss.ts
  client/src/utils/blogUrlToRss.ts
Labels: ✨ Feature
