Repository boostcampwm-2024/web05-Denamu, pull requests merged in 2025-06, with the labels that each got.

#403 ♻️ refactor: feed crawler 로그 수집 개선
  feed-crawler/package-lock.json
  feed-crawler/package.json
  feed-crawler/src/claude.service.ts
  feed-crawler/src/common/logger.ts
Labels: ✨ Feature, 🔨 Refactor, 🧹 Cleanup

#401 ✨ feat: 사용자 활동정보 업데이트 스케줄러 작성
  server/src/user/module/user.module.ts
  server/src/user/scheduler/user.scheduler.ts
Labels: ✨ Feature

#409 ✨ feat: 좋아요 API 구현
  docker-compose/docker-compose.infra.yml
  docker-compose/docker-compose.prod.infra.yml
  docker-compose/init.sql
  feed-crawler/src/repository/feed.repository.ts
  server/src/app.module.ts
  server/src/comment/module/comment.module.ts
  server/src/comment/repository/comment.repository.ts
  server/src/comment/service/comment.service.ts
  server/src/common/auth/jwt.interceptor.ts
  server/src/common/auth/jwt.module.ts
  server/src/common/guard/jwt.guard.ts
  server/src/feed/api-docs/readFeedDetail.api-docs.ts
  server/src/feed/api-docs/readFeedPagination.api-docs.ts
  server/src/feed/api-docs/readRecentFeedList.api-docs.ts
  server/src/feed/api-docs/readTrendFeedList.api-docs.ts
  server/src/feed/api-docs/searchFeedList.api-docs.ts
  server/src/feed/controller/feed.controller.ts
  server/src/feed/dto/response/feed-detail.dto.ts
  server/src/feed/dto/response/feed-pagination.dto.ts
  server/src/feed/dto/response/recent.dto.ts
  server/src/feed/dto/response/search-feed.dto.ts
  server/src/feed/entity/feed.entity.ts
  server/src/feed/module/feed.module.ts
  server/src/feed/repository/feed.repository.ts
  server/src/feed/service/feed.service.ts
  server/src/like/api-docs/createLike.api-docs.ts
  server/src/like/api-docs/deleteLike.api-docs.ts
  server/src/like/controller/like.controller.ts
  server/src/like/dto/request/like.dto.ts
  server/src/like/entity/like.entity.ts
  server/src/like/module/like.module.ts
  server/src/like/repository/like.repository.ts
  server/src/like/service/like.service.ts
  server/src/migration/1749798749393-FeedLikeAdd.ts
  server/src/migration/1749798966642-LikeCreate.ts
  server/test/fixture/feed.fixture.ts
  server/test/like/dto/like.dto.spec.ts
  server/test/like/e2e/likeCreate.e2e-spec.ts
  server/test/like/e2e/likeDelete.e2e-spec.ts
Labels: ✨ Feature, ✅ Test

#410 🐛 fix: 검색시 디테일 페이지로 이동
  client/src/components/search/SearchResults/SearchResultItem.tsx
  client/src/hooks/common/usePostCardActions.ts
  client/src/pages/PostDetailPage.tsx
Labels: ✨ Feature

#424 ✨ feat: 유저 정보 수정 API 구현
  server/src/user/api-docs/updateUser.api-docs.ts
  server/src/user/controller/user.controller.ts
  server/src/user/dto/request/update-user.dto.ts
  server/src/user/service/user.service.ts
  server/test/user/dto/update-user.dto.spec.ts
  server/test/user/e2e/update-profile.e2e-spec.ts
Labels: ✨ Feature, 📝 Docs
