Repository boostcampwm-2024/web05-Denamu, pull requests merged in 2025-05, with the labels that each got.

#384 🐛 fix: 메일 내 회원 가입완료 링크 수정
  server/src/common/email/email.service.ts
Labels: 👹 BugFix

#386 📦 chore: 태그 및 요약 내용, 개발용 사용자 계정 추가
  docker-compose/init.sql
Labels: 🔧 Chore

#388 🐛 fix: tag insert 에러 수정
  feed-crawler/src/repository/tag-map.repository.ts
  server/src/common/database/load.config.ts
Labels: 👹 BugFix

#385 ✨ feat: 댓글 등록, 수정, 삭제 기능 API 및 테스트 코드 작성
  server/src/admin/module/admin.module.ts
  server/src/app.module.ts
  server/src/comment/api-docs/createComment.api-docs.ts
  server/src/comment/api-docs/deleteComment.api-docs.ts
  server/src/comment/api-docs/updateComment.api-docs.ts
  server/src/comment/controller/comment.controller.ts
  server/src/comment/dto/request/create-comment.dto.ts
  server/src/comment/dto/request/delete-comment.dto.ts
  server/src/comment/dto/request/update-comment.dto.ts
  server/src/comment/entity/comment.entity.ts
  server/src/comment/module/comment.module.ts
  server/src/comment/repository/comment.repository.ts
  server/src/comment/service/comment.service.ts
  server/src/common/guard/jwt.guard.ts
  server/src/feed/module/feed.module.ts
  server/src/migration/1746169800168-CommentCreate.ts
  server/src/user/module/user.module.ts
  server/src/user/service/user.service.ts
  server/test/comment/dto/comment-create.dto.spec.ts
  server/test/comment/dto/comment-delete.dto.spec.ts
  server/test/comment/dto/comment-update.dto.spec.ts
  server/test/comment/e2e/create.e2e-spec.ts
  server/test/comment/e2e/delete.e2e-spec.ts
  server/test/comment/e2e/update.e2e-spec.ts
  server/test/fixture/comment.fixture.ts
  server/test/user/e2e/logout.e2e-spec.ts
  server/test/user/e2e/refresh-token.e2e-spec.ts
Labels: ✨ Feature, ✅ Test

#376 ✨ feat: 포스트 필터링 및 추천 포스트 구현
  client/src/api/services/posts.ts
  client/src/components/common/Card/PostCard.tsx
  client/src/components/common/Card/PostCardGrid.tsx
  client/src/components/common/SectionHeader.tsx
  client/src/components/filter/Filter.tsx
  client/src/components/sections/AnimatedPostGrid.tsx
  client/src/components/sections/LatestSection.tsx
  client/src/constants/filter.ts
  client/src/hooks/common/useRecentTag.ts
  client/src/hooks/common/useUpdateRecentTag.ts
  client/src/hooks/queries/useInfiniteScrollQuery.ts
  client/src/store/useFilterStore.ts
  client/src/store/usePostTypeStore.ts
Labels: ✨ Feature

#392 ✨ feat: Github OAuth 회원가입 API 구현
  server/src/user/api-docs/oAuth.api-docs.ts
  server/src/user/constant/oauth.constant.ts
  server/src/user/controller/oauth.controller.ts
  server/src/user/dto/request/oauth-type.dto.ts
  server/src/user/module/user.module.ts
  server/src/user/provider/github.provider.ts
  server/src/user/provider/google.provider.ts
  server/src/user/provider/oauth-provider.interface.ts
  server/src/user/service/oauth.service.ts
Labels: ✨ Feature

#395 📦 chore: docker builder 운영 환경 용량 부족 문제 해결
  .github/workflows/deploy_feed-crawler.yml
  .github/workflows/deploy_server.yml
Labels: 🔧 Chore

#391 ✨ feat: 프로메테우스 + 그라파나 모니터링 시스템 구축
  docker-compose/docker-compose.prod.infra.yml
  docker-compose/prometheus.yml
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/chat/chat.gateway.ts
  server/src/common/logger/logger.interceptor.ts
  server/src/common/metrics/metrics.interceptor.ts
  server/src/common/metrics/metrics.module.ts
Labels: ✨ Feature, 🔧 Chore

#394 ✅ test: claude ai 테스트 코드 작성
  feed-crawler/package-lock.json
  feed-crawler/package.json
  feed-crawler/src/claude.service.ts
  feed-crawler/src/common/redis-access.ts
  feed-crawler/src/common/sqlite-access.ts
  feed-crawler/src/repository/feed.repository.ts
  feed-crawler/test/claude-ai.e2e-spec.ts
  feed-crawler/test/feed-crawling.e2e-spec.ts
  feed-crawler/test/jest-integration.json
  feed-crawler/test/jest.setup.ts
  feed-crawler/test/setup/jest.global-setup.ts
  feed-crawler/test/setup/jest.global-teardown.ts
  feed-crawler/test/setup/testContext.setup.ts
  feed-crawler/test/setup/truncate-tables.setup.ts
  server/test/jest.setup.ts
Labels: ✅ Test, 🔨 Refactor

#397 ✨ feat: oauth 로그인 처리 추가
  server/src/user/controller/oauth.controller.ts
  server/src/user/service/oauth.service.ts
Labels: ✨ Feature

#398 ✨ feat: oauth provider 마이그레이션 파일 작성
  server/src/migration/1747678294586-CreateProvider.ts
Labels: ✨ Feature
