Repository boostcampwm-2024/web05-Denamu, pull requests merged in 2025-07, with the labels that each got.

#429 📦 chore: 마이그레이션 파일 처음부터 작성
  server/src/migration/1619999999993-CreateAdmin.ts
  server/src/migration/1619999999994-CreateRss.ts
  server/src/migration/1619999999995-CreateRssAccept.ts
  server/src/migration/1619999999996-CreateRssReject.ts
  server/src/migration/1619999999997-CreateFeed.ts
  server/src/migration/1619999999998-CreateUser.ts
  server/src/migration/1619999999999-CreateActivity.ts
  server/src/migration/1746169800168-CreateComment.ts
  server/src/migration/1747678294586-CreateProvider.ts
  server/src/migration/1748420270110-UpdateUserColumns.ts
  server/src/migration/1749798749393-FeedLikeAdd.ts
  server/src/migration/1749798749400-CreateFeedView.ts
  server/src/migration/1749798966642-CreateLike.ts
Labels: 🔧 Chore

#428 ✨ feat: RSS 삭제 신청 조회 API 구현
  docker-compose/init.sql
  server/src/admin/entity/admin.entity.ts
  server/src/common/swagger/swagger.ts
  server/src/migration/1749798966642-CreateLike.ts
  server/src/migration/1751373592194-CreateRssRemove.ts
  server/src/migration/1752060032219-RenameLikeForeignKey.ts
  server/src/rss/api-docs/readDeleteRequest.api-docs.ts
  server/src/rss/controller/rss.controller.ts
  server/src/rss/entity/rss-remove.entity.ts
  server/src/rss/entity/rss.entity.ts
  server/src/rss/module/rss.module.ts
  server/src/rss/repository/rss-remove.repository.ts
  server/src/rss/repository/rss.repository.ts
  server/src/rss/service/rss.service.ts
  server/test/rss/e2e/remove.e2e-spec.ts
Labels: ✨ Feature, ✅ Test

#433 ✨ feat: RSS 삭제 신청 API 구현
  server/env/.env.local
  server/src/common/email/email.service.ts
  server/src/common/email/mail_content.ts
  server/src/migration/1619999999996-CreateRssReject.ts
  server/src/migration/1620000000000-CreateTag.ts
  server/src/migration/1620000000000-MigrateTagsToManyToMany.ts
  server/src/migration/1749798966642-CreateLike.ts
  server/src/migration/1752060032219-RenameLikeForeignKey.ts
  server/src/migration/1752238606597-DeleteRssRemove.ts
  server/src/rss/api-docs/readDeleteRequest.api-docs.ts
  server/src/rss/api-docs/requestDeleteRss.api-docs.ts
  server/src/rss/controller/rss.controller.ts
  server/src/rss/dto/request/rss-remove.dto.ts
  server/src/rss/entity/rss-remove.entity.ts
  server/src/rss/module/rss.module.ts
  server/src/rss/repository/rss-remove.repository.ts
  server/src/rss/service/rss.service.ts
  server/test/rss/dto/rss-remove.dto.spec.ts
  server/test/rss/e2e/remove.e2e-spec.ts
Labels: ✨ Feature

#434 ✨ feat: RSS 삭제 인증 API 구현
  server/src/migration/1752060032219-RenameLikeForeignKey.ts
  server/src/rss/api-docs/deleteRss.api-docs.ts
  server/src/rss/controller/rss.controller.ts
  server/src/rss/dto/request/rss-delete.dto.ts
  server/src/rss/dto/request/rss-request-delete.dto.ts
  server/src/rss/service/rss.service.ts
  server/test/rss/dto/rss-delete.dto.spec.ts
  server/test/rss/dto/rss-remove.dto.spec.ts
  server/test/rss/e2e/remove.e2e-spec.ts
Labels: ✨ Feature

#436 📦 chore: docker-compose production 환경 인프라 추가시 자동 배포 구현
  .github/workflows/deploy_infra.yml
Labels: 🔧 Chore

#441 ♻️ refactor: 이름 변경 및 필요없는 코드 제거, 디렉토리 경로 변경
  server/src/activity/module/activity.module.ts
  server/src/admin/controller/admin.controller.ts
  server/src/app.module.ts
  server/src/common/auth/jwt.module.ts
  server/src/common/database/load.config.ts
  server/src/common/database/migration/1619999999993-CreateAdmin.ts
  server/src/common/database/migration/1619999999994-CreateRss.ts
  server/src/common/database/migration/1619999999995-CreateRssAccept.ts
  server/src/common/database/migration/1619999999996-CreateRssReject.ts
  server/src/common/database/migration/1619999999997-CreateFeed.ts
  server/src/common/database/migration/1619999999998-CreateUser.ts
  server/src/common/database/migration/1619999999999-CreateActivity.ts
  server/src/common/database/migration/1620000000000-CreateTag.ts
  server/src/common/database/migration/1746169800168-CreateComment.ts
  server/src/common/database/migration/1747678294586-CreateProvider.ts
  server/src/common/database/migration/1749798749400-CreateFeedView.ts
  server/src/common/database/migration/1749798966642-CreateLike.ts
  server/src/common/database/migration/1751373592194-CreateRssRemove.ts
  server/src/common/database/migration/1752060032219-RenameLikeForeignKey.ts
  server/src/common/database/migration/1752238606597-DeleteRssRemove.ts
  server/src/common/guard/auth.guard.ts
  server/src/feed/module/feed.module.ts
  server/src/feed/service/feed-crawler.service.ts
  server/src/like/module/like.module.ts
  server/src/rss/api-docs/deleteRss.api-docs.ts
  server/src/rss/controller/rss.controller.ts
  server/src/rss/module/rss.module.ts
  server/src/rss/service/rss.service.ts
  server/src/statistic/module/statistic.module.ts
  server/src/user/service/oauth.service.ts
Labels: 🔨 Refactor

#442 ✨ feat: 깃헙 oauth 클라이언트 환경변수 추가
  .github/workflows/deploy_server.yml
Labels: ✨ Feature, 👹 BugFix
