Repository boostcampwm-2024/web05-Denamu, pull requests merged in 2025-04, with the labels that each got.

#370 🐛 fix: 유저 인증 로직에 레디스 키 삭제 구문 추가
  server/src/user/service/user.service.ts
Labels: 👹 BugFix

#363 🐛 fix: 바 차트 툴팁 조회수, 색상 박스 변경
  client/src/components/chart/BarChartItem.tsx
Labels: 👹 BugFix

#372 🐛 fix: 트랜딩 포스트가 없을 때 EmptyPost 컴포넌트가 나오지 않던 버그 수정 & 스켈레톤 UI가 나오지 않던 버그 수정
  client/src/components/common/Card/PostCardSkeleton.tsx
  client/src/components/sections/AnimatedPostGrid.tsx
  client/src/components/sections/TrendingSection.tsx
Labels: 👹 BugFix

#367 ✨ feat: 로그아웃, Access Token 재발급 API 구현
  .github/workflows/deploy_server.yml
  server/env/.env.local
  server/package-lock.json
  server/package.json
  server/src/common/auth/jwt.module.ts
  server/src/common/auth/jwt.strategy.ts
  server/src/common/guard/jwt.guard.ts
  server/src/user/api-docs/logoutUser.api-docs.ts
  server/src/user/api-docs/refreshUser.api-docs.ts
  server/src/user/controller/user.controller.ts
  server/src/user/entity/user.entity.ts
  server/src/user/module/user.module.ts
  server/src/user/service/user.service.ts
  server/test/integration-test-global-setup.ts
Labels: ✨ Feature, 📝 Docs

#378 ✨ feat: 채팅 낙관적 업데이트를 지원하기 위한 채팅 페이로드 변경
  server/src/chat/chat.gateway.ts
  server/src/chat/chat.type.ts
  server/src/chat/scheduler/chat.scheduler.ts
Labels: ✨ Feature

#369 ✨ feat: Google OAuth 회원가입 API 구현
  .github/workflows/deploy_server.yml
  package-lock.json
  server/package-lock.json
  server/package.json
  server/src/common/swagger/swagger.ts
  server/src/user/api-docs/googleOAuth.api-docs.ts
  server/src/user/api-docs/oauthCallback.api-docs.ts
  server/src/user/constant/oauth.constant.ts
  server/src/user/controller/oauth.controller.ts
  server/src/user/entity/provider.entity.ts
  server/src/user/entity/user.entity.ts
  server/src/user/module/user.module.ts
  server/src/user/provider/google.provider.ts
  server/src/user/provider/oauth-provider.interface.ts
  server/src/user/repository/provider.repository.ts
  server/src/user/service/oauth.service.ts
Labels: ✨ Feature, 📝 Docs

#374 ♻️ refactor: tag 테이블 구조 변경
  feed-crawler/src/claude.service.ts
  feed-crawler/src/repository/tag-map.repository.ts
  server/data-source.ts
  server/src/common/database/load.config.ts
  server/src/feed/entity/feed.entity.ts
  server/src/feed/entity/tag-map.entity.ts
  server/src/feed/module/feed.module.ts
  server/src/migration/MigrateTagsToManyToMany1620000000000.ts
  server/src/tag/entity/tag.entity.ts
  server/src/tag/module/tag.module.ts
  server/src/tag/repository/tag.repository.ts
  server/test/feed/e2e/feed-detail.e2e-spec.ts
  server/test/fixture/tag-map.fixture.ts
Labels: 🔨 Refactor

#381 🐛 fix: 도커 실행 명령 수정
  package.json
Labels: 👹 BugFix, 🔧 Chore

#382 🐛 fix: Collation이 다르게 적용되던 부분 수정
  server/src/migration/MigrateTagsToManyToMany1620000000000.ts
Labels: 👹 BugFix
